name: test-and-linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # Ставим зависимости
      - run: npm install
      # Запускаем линтер
      - name: run lint
        run: make lint
      - name: run tests
        run: make test
